### ISSUE TITLE
Future of this PEP

### ISSUE THREAD

**Issue by srittau** [srittau/type-stub-pep#102]
Since so far I had no luck finding a mentor, I see two ways forward:

* I can look harder for a mentor, for example by posting to python-dev asking whether someone is willing to mentor this.
* We could try to integrate this document into the larger "Python Type Documentation" that @JelleZijlstra and @shannonzhu suggested.

What do you think is the best way forward?

**Comment by JelleZijlstra** [comment]
We could ask the Steering Council to allow a non-core dev sponsor. I'm a PEP editor, so I could plausibly be a sponsor too.

But I also like the idea of including this document in the larger typing documentation project. It would be a good fit as an area for standardization among type checkers.

**Comment by srittau** [comment]
I'd like to hear what @rchen152  and @Solumin think, but thinking about it the typing documentation is not the perfect fit, and a PEP is the better alternative. We have some user documentation in here, but I think overall this PEP is quite technical.

**Comment by gvanrossum** [comment]
I don't want to stand in the way of this becoming a PEP, if that's what you
all think it should be, so I would act as a last-resort sponsor, but I
don't have time to review it (as you say, it's quite long and technical).
In that case I would recommend to make it an informational PEP, which makes
it easier to get it in without asking the Steering Council to accept it.

But I think you ought to explore non-PEP options first.

**Comment by rchen152** [comment]
Are there advantages of making this a PEP rather than incorporating it into centralized typing documentation? From my point of view, the important thing is that the contents of this document end up somewhere (1) visible and (2) official. Either option seems like it would satisfy those points, so I'd be inclined to go with whichever seems more feasible, which at the moment seems to be the non-PEP route.

**Comment by Solumin** [comment]
I agree with Rebecca: Visibility and an official stamp-of-approval are
important. A PEP would absolutely grant that. All else being equal, I'd
push for a PEP, since the goal of the typing documentation is to gather all
the typing-related PEPs in an easy-to-discover place. However, the non-PEP
route does seem to be more feasible.

If we do go the non-PEP route, will the community still take the guidelines
seriously?

**Comment by gvanrossum** [comment]
On Wed, May 19, 2021 at 9:22 PM Teddy Sudol ***@***.***>
wrote:

> If we do go the non-PEP route, will the community still take the guidelines
> seriously?
>

This is of course the $(1<<20) question.

In particular, an open question is whether special behaviors that we want
to use in stubs will be implemented reasonably promptly by all type
checkers. And whether it would make a difference if the behavior was
specified in a PEP or not.

(For *syntactic* features there's no doubt that a PEP is needed. But here
we are talking about allowability and meaning of existing syntax. For
example, what can be put in the body of a function or method? Only 'pass'
or '...' or anything that's a valid Python block?)

-- 
--Guido van Rossum (python.org/~guido)

**Comment by srittau** [comment]
@JelleZijlstra @rchen152 @Solumin If you agree, I would like to integrate the PEP into the docs at https://github.com/python/typing. (Well, there aren't any docs at the moment, but @shannonzhu prepared the repository for that.)

**Comment by rchen152** [comment]
Sounds like a good place for it! (And hopefully it'll inspire some more content :) )

**Comment by Solumin** [comment]
Yes, I agree, that would be a good place for it.

**Comment by srittau** [comment]
It's been merged now. Thank you everybody! It took a long time, and it didn't end up where we originally planned it to end up, but in the end I think we found a good spot for it, where it can be useful for everyone and evolve naturally.

**Comment by rchen152** [comment]
:partying_face: Thank you for seeing this through!
