### ISSUE TITLE
@overload restrictions?

### ISSUE THREAD

**Issue by rchen152** [srittau/type-stub-pep#15]
While working on https://github.com/python/typeshed/pull/2464, I noticed that mypy does some checks on overloaded signatures, I assume to prevent things like incompatible or redundant signatures. Would it make sense to document/formalize these?

**Comment by JelleZijlstra** [comment]
I think it does, but I'm not sure it makes sense as part of a PEP on stubs, because overloads should mostly behave the same in stubs and implementation files. (I think the only difference should be that in stubs no implementation is required.) I believe Michael Lee has some plans to work on a PEP formalizing overload semantics.

**Comment by rchen152** [comment]
Ah, good point. And the "function bodies should be `...`" part of the style section already covers the fact that no implementation is required.
