### ISSUE TITLE
Supported Constructs: __all__

### ISSUE THREAD

**Issue by srittau** [srittau/type-stub-pep#20]
This came up in #19: Should `__all__` be supported in stubs? Currently [mypy's guidelines](https://github.com/python/mypy/wiki/Creating-Stubs-For-Python-Modules) recommend not to use them, but as @JelleZijlstra points out they might be useful in stubs.

**Comment by JukkaL** [comment]
The guideline in mypy docs only say that generally it shouldn't be included, since it's usually not useful and makes stubs harder to maintain. I think that it should be acceptable under specific circumstances, but only if there is a compelling reason. Here's a hypothetical use case:

* Stub for `foo` contains a certain private definition that some real-world code depends on for some reason.
* The module defines `__all__` and the private definition is not included there.
* The private definition has a name that is likely to conflict with other names (say, `initialize`).

If there's no `__all__`, then `from foo import *` may cause false positives, since the private definition may conflict with other things that happen to have the same name. 

If the name of the private definition is long/obscure, it may not be worthwhile to add `__all__`, since for a conflict to happen two infrequent events need to happen together, which we perhaps shouldn't worry about:
* Somebody uses `from foo import *` (star imports are avoided by most people most of the time).
* There is a name conflict with another definition.

**Comment by rchen152** [comment]
If we follow the mypy docs, it sounds like the guideline should be that `__all__` should only be included in a stub file if needed to avoid exposing a private definition, which seems fine - I don't have a strong opinion on this.

**Comment by Solumin** [comment]
I wonder if `__all__` should imply that the stub file should only contain hints for things included in `__all__`. The stub file does essentially define the public interface of the module, which is pretty much what `__all__` does too. Should we recommend that?

I agree that `__all__` could be useful in a stub file to avoid exposing a private definition.

**Comment by rchen152** [comment]
We concluded that `__all__` should be supported in stubs. When `__all__` is not present, all non-underscored names are imported by `import *`; when present, everything in `__all__` is imported.
