### ISSUE TITLE
Stub-only classes

### ISSUE THREAD

**Issue by srittau** [srittau/type-stub-pep#21]
Discussion continued from #19.

## The problem

Sometimes, functions and methods return instances of private classes. Poster childs are `re.match()` and `re.compile()`, although those are handled specially in `typing`. There are other examples in the standard library, and I am guilty of having done this in the past myself. In light of type hints this can probably be considered bad practice, but it is still something we have to deal with.

It can be necessary to access the type of these instances, for example when returning such an object from a function.

## Possible Solutions

* Let those functions return `Any`. No type-checking.
* Create a private class in the stub and expect people not to import it. They need to use `Any` or some other workaround if they need to reference the type. Probably not realistic, since people will just import the class from the stub if it's available. Also this loses type-safety unnecessarily.
* Create a private class with the same name as the class in the implementation (if available) and allow people to import it. This has the advantage that people can just import that name and it will work both at runtime and while type checking. But people should probably not do that, since importing (runtime) private classes is dangerous.
* Create a public or private stub-only class that can be imported, but needs an `if TYPE_CHECKING` guard. For the reasons above this is my favorite solution. I have a slight preference for making it public, since it is public in the stub.

In the latter two cases the we should probably mark those classes somehow. I'd suggest a standardized comment like `# stub-only`. We could also make these classes protocols or abstract, but I am not sure this is needed. Another solution is to introduce a special decorator in typing. The latter is my favorite solution, but is something we need to check with the larger typing community.

## Suggested Wording

Based on the last version in the "Private Definitions" section I removed.

```rst
If a function or method returns an instance of a class that is not
available at runtime, the type stub should provide a public, stub-only class
with a ``# stub-only`` comment::

     # stub-only
    class SomeData:
        x: int
        def foo() -> None: ...

     def get_some_data() -> SomeData: ...

Since stub-only classes are not available at runtime, they must be
imported using a guard::

    if typing.TYPE_CHECKING:
        import SomeData from somestub
```

**Comment by Solumin** [comment]
On reflection, I feel like your preferred solution is best. It respects the API's design of having a private class while still allowing it to be used for type checking. I would make it a public class, since it is technically part of the public API. (Which is a design flaw of the API, in my opinion.)

Stub-only classes are also useful for certain odd cases, like functools.partial. For source code like:
```python
def f(x: str, y: int):
  return x + str(y)
g = functools.partial(f, "womble")
```

One way to create the stub hint for `g` is:
```python
class _partial-g-x(functools.partial):
  # All members of functools.partial, but specialized for g.
g: _partial-g-x
```

`_partial-g-x` doesn't _really_ exist, so it would be a perfect candidate for a stub-only class. A `@stubonly` decorator would be better than a comment, IMO.

**Comment by rchen152** [comment]
The primary argument I see against stub-only classes is the special handling required to use them:

* Imports and aliases have to be inside `TYPE_CHECKING`.
* In Python 3.6, annotations have to be quoted.

Part of the problem is that when a user forgets to do the above, they confusingly get an error at runtime rather than checking time. If we do recommend stub-only classes, I'd be a fan of marking them with a decorator, since that would allow a type checker to detect and warn about misuse.

**Comment by Solumin** [comment]
I agree it's absolutely necessary to mark classes as stub-only. A decorator makes mores sense than a comment, because then the class is clearly marked.

**Comment by Kazicata** [comment]
Kazi696
