### ISSUE TITLE
Whether to follow documented types or types accepted in reality

### ISSUE THREAD

**Issue by rchen152** [srittau/type-stub-pep#41]
I noticed the following bullet point under stub content on the wiki page:

> Whether to follow documented types or types accepted in reality. (Documentation may say a function takes "a list", but really it accepts any sequence or even iterable. What should the stub do?)

I don't think we've discussed this yet - what do folks think is the right thing to do? Is there any de facto standard that typeshed already follows?

**Comment by srittau** [comment]
Good question. In the end that is for a maintainer to decide, but I think currently typeshed defaults to the implementation, at least I do when writing stubs. I feel most Python documentation is vague on types, because many developers (myself included) have not given it much thought so far. A "list" is also a concrete type as opposed to an "iterable", which is an abstract concept.

I think we should recommend: Use reality, if in doubt, ask the maintainer.

**Comment by JelleZijlstra** [comment]
I think there are a few cases where reality is too permissive and we should be more precise in types. For example, this recently came up in python/typeshed#2990.

More generally, for pretty much every parameter typed as `bool`, the parameter will in fact accept any Python object with a functional `__bool__` method, since it's probably just going to use the bool in a conditional. But it's still useful for users of typing to type these parameters as just `bool`, so they don't accidentally pass some other type that happens to be bool-compatible.

I do agree with @srittau that documentation is usually vague, and I'd be supportive of following the implementation in the list/iterable case mentioned.

**Comment by srittau** [comment]
@JelleZijlstra Good points, especially about `bool`. It's not really clear-cut, maybe we should not recommend more than "ask author, otherwise use best judgement" with a few examples.

**Comment by rchen152** [comment]
To summarize, it sounds like our stance is:

* When possible, ask the library author about intent in cases in which the documentation and implementation differ.
* Otherwise, use best judgment. Examples:
-> Documentation says list, actually accepts iterable: iterable is usually better because it's an abstract type.
-> Documentation says bool, actually accepts any type with `__bool__`: bool is usually better to prevent accidentally passing other bool-compatible types.

If that seems reasonable, I'll go ahead and take a stab at writing it up.

**Comment by JelleZijlstra** [comment]
I'm a bit hesitant to lean too much on "ask the author", because that can increase the barrier to entry for contributing stubs. So I'd shift the emphasis to "Use best judgment", with the examples you gave, and mention that stub authors can ask library authors if in doubt.
