### ISSUE TITLE
__all__: Require when implementation has it?

### ISSUE THREAD

**Issue by srittau** [srittau/type-stub-pep#67]
We already have a section about `__all__`. Maybe it makes sense to add language to the effect that this should be included in stubs and match the implementation iff the implementation has it. This way, type checkers can check whether `my_module.__all__` is valid.

**Comment by JelleZijlstra** [comment]
This would also have the advantage that type checkers can correctly implement `import *`.

**Comment by rchen152** [comment]
I don't have any objection to requiring `__all__` when it's in the implementation, but I'm not clear on the benefit - when can `my_module.__all__` be invalid?

**Comment by JelleZijlstra** [comment]
It could include names that aren't actually defined at runtime, and as I said above having `__all__` in a stub could enable type checkers to implement `import *` correctly.

**Comment by rchen152** [comment]
I see, thanks!

The current draft already suggests using `__all__` to control `import *` behavior when needed.

I'm still not seeing how a type checker verifying that the names in `__all__` are valid would be valuable. The most common way a stub gets created is that a user of a library contributes it to typeshed. A user makes a stub, follows the recommendation to copy `__all__` over from the source, and finds that it includes an invalid name - then what? They could reach out to the library authors to get the problem fixed, but that feels more like an unrelated cleanup rather than progress toward the goal of supporting type-checking for users of the library.

**Comment by srittau** [comment]
To me, mandating this has two advantages:
* Controlling star important behavior.
* Type checkers can check whether `module.__all__` exists. Not mandating has led to inconsistent use in stubs in the past. (Not included, included, or just annotated as `__all__:List[str]`.)

**Comment by rchen152** [comment]
Sure, mandating it for consistency sounds fine to me :)

**Comment by srittau** [comment]
#69
