### ISSUE TITLE
How to treat errors in stub

### ISSUE THREAD

**Issue by JelleZijlstra** [srittau/type-stub-pep#9]
An issue that has come up in mypy is how to treat type errors detected in stubs. This is a problem because type checkers may report different errors depending on the installed version and on strictness options, so it's hard for stub authors to ensure that their code will never be rejected by any type checker. And for end user, it's hard to deal with errors that come from third-party packages.

Perhaps we could include a recommendation to silence errors in third-party stubs by default, which is now mypy's behavior. Or perhaps this recommendation belongs in PEP 561 instead.

**Comment by rchen152** [comment]
When mypy finds an error in a stub, is the error reported in the stub itself or where the stub is used? I'm asking because pytype does the latter; if the stub for `foo` isn't parseable, you'll get a pyi error on `import foo`. I'd argue that that's a valuable error that shouldn't be silenced by default, since it warns that no checking is being done against `foo`, and the user is free to put a `# type: ignore` there anyway. On the other hand, if errors are being reported inside third party stubs over which the user has no control, then I agree with the recommendation to silence them.

**Comment by JelleZijlstra** [comment]
Mypy reports the error in the stub itself.

Errors where stub cannot be parsed perhaps should still be given, but mypy at least has a range of additional strictness options that could cause errors in conforming stubs. (For example, it optionally gives an error if you use `List` without a type parameter.)

**Comment by rchen152** [comment]
Thanks for the clarification. I guess an unparseable stub would be non-conforming, so the recommendation should be to never report errors in/for conforming third party stubs?

**Comment by rchen152** [comment]
We concluded that this should be left as an implementation detail to individual type checkers.
