### ISSUE TITLE
Default parameter values in type stubs

### ISSUE THREAD

**Issue by erictraut** [srittau/type-stub-pep#92]
Related to #88 (which discusses docstring inclusion in type stubs), I'd like to suggest similar language for default parameter values. In cases where the associated library is implemented in a language other than Python, the stub is the only source of information for a static analyzer that wants to present help text about a function/method signature, and default parameter values are an important part of that signature. Displaying `def foo(x = None) -> None` is way more useful than `def foo(x = ...) -> None`.

**Comment by srittau** [comment]
+1 I'll prepare a PR when #97 gets merged. (To prevent conflicts.)

My plan is:
* Allow either `...` or the actual default value.
* Recommend (for now) `...`

The recommendation for `...` is just because that's the current status quo and I don't want to change that with the first iteration of the PEP. That said, the good thing about this PEP is that discussions in typing-sig can be much more concrete in the future. I.e. a new discussion can be started with a concrete proposal to change this PEP in a certain way. And changing the defaults looks like a prime candidate for that.

**Comment by srittau** [comment]
This has been merged now.
